### ISSUE TITLE
ORA-01034: ORACLE not available on prepared image

### ISSUE THREAD

**Issue by gerbil** [KamilJedrzejuk/oracle18c-xe#1]
Database does not exists, configuring
```
Oracle Database instance XE is already configured.
The Oracle base remains unchanged with value /opt/oracle
Enabling XDB for external access

SQL*Plus: Release 18.0.0.0.0 - Production on Thu Apr 16 13:59:59 2020
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Connected to an idle instance.

SQL> BEGIN dbms_xdb_config.setlistenerlocalaccess(false); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> BEGIN dbms_xdb_config.setglobalportenabled(true); END;

*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
```

**Comment by KamilJedrzejuk** [comment]
What is your goal
Unfortunately, I suppose a Docker change will be required in this case.

**Comment by gerbil** [comment]
Goal is to run already created DB without need to prepare DB for a 30minutes every time..
So, im trying to run init container provided, but it failed on startup.

**Comment by KamilJedrzejuk** [comment]
@gerbil  
I'll check this problem. I tested my image and had no problems.

**Comment by KamilJedrzejuk** [comment]
@gerbil 
Did You try this: 
https://hub.docker.com/r/kamiljedrzejuk/oracle18c-xe-initialized

**Comment by gerbil** [comment]
That's exactly what i've tried.. but it's just failed on startup every time.

**Comment by gerbil** [comment]
Even after fixing permission issue using wo;
sed -i -r 's/^(session\s+required\s+pam_limits.so)/#\1/' /etc/pam.d/* 

I still can't see oracle working:
Database exists
Starting Oracle Net Listener.
Oracle Net Listener started.
Starting Oracle Database instance XE.
Oracle Database instance XE started.

The Oracle base remains unchanged with value /opt/oracle
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Pluggable database XEPDB1 opened read write
Completed: alter pluggable database XEPDB1 open
2020-03-16T18:40:14.966076+00:00
XEPDB1(3):CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/XE/XEPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
XEPDB1(3):Completed: CREATE SMALLFILE TABLESPACE "USERS" LOGGING  DATAFILE  '/opt/oracle/oradata/XE/XEPDB1/users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED  EXTENT MANAGEMENT LOCAL  SEGMENT SPACE MANAGEMENT  AUTO
XEPDB1(3):ALTER DATABASE DEFAULT TABLESPACE "USERS"
XEPDB1(3):Completed: ALTER DATABASE DEFAULT TABLESPACE "USERS"
2020-03-16T18:40:16.125468+00:00
ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE
Completed: ALTER PLUGGABLE DATABASE XEPDB1 SAVE STATE

**Comment by gerbil** [comment]
Script to check DB health:

`bash-4.2# su oracle -c '$ORACLE_HOME/bin/sqlplus -s / as sysdba' << EOF
>    set heading off;
>    set pagesize 0;
>    SELECT open_mode FROM v\\$pdbs WHERE name COLLATE BINARY_CI = '$ORACLE_PDB';
>    exit;
> EOF
   SELECT open_mode FROM v\ WHERE name COLLATE BINARY_CI = ''
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0`

**Comment by gerbil** [comment]
Just found a bug/issue with wo for this:
docker run should include --cpuset-cpus=0-7 in order to successfully start an Oracle instance.. dunno why, but it's working! thank you!

**Comment by KamilJedrzejuk** [comment]
@gerbil  So problem was with your environment?
