### ISSUE TITLE
Creating an image with existing data

### ISSUE THREAD

**Issue by serpro69** [KamilJedrzejuk/oracle18c-xe#3]
Hi,

Have you tried modifying your Dockerfile to have the dockerized DB contain schemas/tables rather than an empty DB?
If so can you provide instructions in the readme?

**Comment by KamilJedrzejuk** [comment]
You can use a additional tool like liquibase. 
Do You wants to have a initialized docker image with your schema and maybe some data.

**Comment by serpro69** [comment]
Yes, I want the docker image to already contain the tables and data.
I think I can commit the data and update the image afterwards.
Anyways, I think I've found a solution now Thanks!
